version: "3"

services:
  redis:
    image: redis
    networks:
      - back-tier

  app-python:
    image: wergfwegsffs/sisrec_py
    build:
      context: ./app-python
    depends_on:
      - redis
    ports:
      - "5010:5010"
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - back-tier

  # web:
  #   image: php:7-apache
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - API_ENDPOINT=http://app-python:5010/api/
  #   volumes:
  #     - ./www:/var/www/html
  #   networks:
  #     - back-tier
  #     - front-tier

  app-dotnet:
    image: wergfwegsffs/sisrec_worker
    build:
      context: ./app-dotnet
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  frontend:
    build:
      context: ./app-node
    environment:
      - HOST=db
    networks:
      - back-tier
      - front-tier
    ports:
      - "3001:3001"
    depends_on:
      - app-dotnet
      - db

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
