version: "3"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  app-python:
    build:
      context: ./app-python
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
