version: "3"

services:
  redis:
    image: redis

  app-python:
    build:
      context: ./app-python
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
